version: '3.8'

services:
  attack-path-engine:
    build: .
    container_name: attack-path-engine
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.7}
    volumes:
      - ./app:/app/app  # Mount for development hot-reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

# Optional: Add Redis for caching (future enhancement)
# redis:
#   image: redis:7-alpine
#   container_name: attack-path-cache
#   ports:
#     - "6379:6379"
#   restart: unless-stopped
